"""redifinicion de la varible'hashed_password' a simplemente 'senha'

Revision ID: 1957ec17e554
Revises: bf1991915206
Create Date: 2025-12-25 17:28:09.384973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1957ec17e554'
down_revision: Union[str, Sequence[str], None] = 'bf1991915206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
