"""elimine owner y buyer de la db

Revision ID: 9d073a43bf82
Revises: 1957ec17e554
Create Date: 2026-01-13 22:03:54.076919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d073a43bf82'
down_revision: Union[str, Sequence[str], None] = '1957ec17e554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('items_owner_id_fkey'), 'items', type_='foreignkey')
    op.drop_column('items', 'owner_id')
    op.drop_constraint(op.f('orders_buyer_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_owner_id_fkey'), 'orders', type_='foreignkey')
    op.drop_column('orders', 'owner_id')
    op.drop_column('orders', 'buyer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('buyer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('orders_owner_id_fkey'), 'orders', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(op.f('orders_buyer_id_fkey'), 'orders', 'users', ['buyer_id'], ['id'])
    op.add_column('items', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('items_owner_id_fkey'), 'items', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
