"""intial migration

Revision ID: bf1991915206
Revises: 
Create Date: 2025-12-24 21:35:52.696646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf1991915206'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('price', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_items_price'), 'items', ['price'], unique=False)
    op.add_column('orders', sa.Column('price', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_price'), 'orders', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_price'), table_name='orders')
    op.drop_column('orders', 'price')
    op.drop_index(op.f('ix_items_price'), table_name='items')
    op.drop_column('items', 'price')
    # ### end Alembic commands ###
